-- Species catalog for BirdQuest — GENERATED, do not edit by hand.
-- Source: bird-model/checkpoints/best.pth  (200 CUB-200 classes)
-- Regenerate: bird-model/.venv/bin/python supabase/scripts/gen_species_seed.py
--
-- class_index is the join key to model predictions (POST /predict).
-- All species seeded at the Common tier (1 pt); rarity_tier is nullable and
-- refined from eBird frequency data later.

insert into public.species (class_index, common_name, scientific_name, rarity_tier, points)
values
  (0, 'Black footed Albatross', NULL, 'Common', 1),
  (1, 'Laysan Albatross', NULL, 'Common', 1),
  (2, 'Sooty Albatross', NULL, 'Common', 1),
  (3, 'Groove billed Ani', NULL, 'Common', 1),
  (4, 'Crested Auklet', NULL, 'Common', 1),
  (5, 'Least Auklet', NULL, 'Common', 1),
  (6, 'Parakeet Auklet', NULL, 'Common', 1),
  (7, 'Rhinoceros Auklet', NULL, 'Common', 1),
  (8, 'Brewer Blackbird', NULL, 'Common', 1),
  (9, 'Red winged Blackbird', NULL, 'Common', 1),
  (10, 'Rusty Blackbird', NULL, 'Common', 1),
  (11, 'Yellow headed Blackbird', NULL, 'Common', 1),
  (12, 'Bobolink', NULL, 'Common', 1),
  (13, 'Indigo Bunting', NULL, 'Common', 1),
  (14, 'Lazuli Bunting', NULL, 'Common', 1),
  (15, 'Painted Bunting', NULL, 'Common', 1),
  (16, 'Cardinal', NULL, 'Common', 1),
  (17, 'Spotted Catbird', NULL, 'Common', 1),
  (18, 'Gray Catbird', NULL, 'Common', 1),
  (19, 'Yellow breasted Chat', NULL, 'Common', 1),
  (20, 'Eastern Towhee', NULL, 'Common', 1),
  (21, 'Chuck will Widow', NULL, 'Common', 1),
  (22, 'Brandt Cormorant', NULL, 'Common', 1),
  (23, 'Red faced Cormorant', NULL, 'Common', 1),
  (24, 'Pelagic Cormorant', NULL, 'Common', 1),
  (25, 'Bronzed Cowbird', NULL, 'Common', 1),
  (26, 'Shiny Cowbird', NULL, 'Common', 1),
  (27, 'Brown Creeper', NULL, 'Common', 1),
  (28, 'American Crow', NULL, 'Common', 1),
  (29, 'Fish Crow', NULL, 'Common', 1),
  (30, 'Black billed Cuckoo', NULL, 'Common', 1),
  (31, 'Mangrove Cuckoo', NULL, 'Common', 1),
  (32, 'Yellow billed Cuckoo', NULL, 'Common', 1),
  (33, 'Gray crowned Rosy Finch', NULL, 'Common', 1),
  (34, 'Purple Finch', NULL, 'Common', 1),
  (35, 'Northern Flicker', NULL, 'Common', 1),
  (36, 'Acadian Flycatcher', NULL, 'Common', 1),
  (37, 'Great Crested Flycatcher', NULL, 'Common', 1),
  (38, 'Least Flycatcher', NULL, 'Common', 1),
  (39, 'Olive sided Flycatcher', NULL, 'Common', 1),
  (40, 'Scissor tailed Flycatcher', NULL, 'Common', 1),
  (41, 'Vermilion Flycatcher', NULL, 'Common', 1),
  (42, 'Yellow bellied Flycatcher', NULL, 'Common', 1),
  (43, 'Frigatebird', NULL, 'Common', 1),
  (44, 'Northern Fulmar', NULL, 'Common', 1),
  (45, 'Gadwall', NULL, 'Common', 1),
  (46, 'American Goldfinch', NULL, 'Common', 1),
  (47, 'European Goldfinch', NULL, 'Common', 1),
  (48, 'Boat tailed Grackle', NULL, 'Common', 1),
  (49, 'Eared Grebe', NULL, 'Common', 1),
  (50, 'Horned Grebe', NULL, 'Common', 1),
  (51, 'Pied billed Grebe', NULL, 'Common', 1),
  (52, 'Western Grebe', NULL, 'Common', 1),
  (53, 'Blue Grosbeak', NULL, 'Common', 1),
  (54, 'Evening Grosbeak', NULL, 'Common', 1),
  (55, 'Pine Grosbeak', NULL, 'Common', 1),
  (56, 'Rose breasted Grosbeak', NULL, 'Common', 1),
  (57, 'Pigeon Guillemot', NULL, 'Common', 1),
  (58, 'California Gull', NULL, 'Common', 1),
  (59, 'Glaucous winged Gull', NULL, 'Common', 1),
  (60, 'Heermann Gull', NULL, 'Common', 1),
  (61, 'Herring Gull', NULL, 'Common', 1),
  (62, 'Ivory Gull', NULL, 'Common', 1),
  (63, 'Ring billed Gull', NULL, 'Common', 1),
  (64, 'Slaty backed Gull', NULL, 'Common', 1),
  (65, 'Western Gull', NULL, 'Common', 1),
  (66, 'Anna Hummingbird', NULL, 'Common', 1),
  (67, 'Ruby throated Hummingbird', NULL, 'Common', 1),
  (68, 'Rufous Hummingbird', NULL, 'Common', 1),
  (69, 'Green Violetear', NULL, 'Common', 1),
  (70, 'Long tailed Jaeger', NULL, 'Common', 1),
  (71, 'Pomarine Jaeger', NULL, 'Common', 1),
  (72, 'Blue Jay', NULL, 'Common', 1),
  (73, 'Florida Jay', NULL, 'Common', 1),
  (74, 'Green Jay', NULL, 'Common', 1),
  (75, 'Dark eyed Junco', NULL, 'Common', 1),
  (76, 'Tropical Kingbird', NULL, 'Common', 1),
  (77, 'Gray Kingbird', NULL, 'Common', 1),
  (78, 'Belted Kingfisher', NULL, 'Common', 1),
  (79, 'Green Kingfisher', NULL, 'Common', 1),
  (80, 'Pied Kingfisher', NULL, 'Common', 1),
  (81, 'Ringed Kingfisher', NULL, 'Common', 1),
  (82, 'White breasted Kingfisher', NULL, 'Common', 1),
  (83, 'Red legged Kittiwake', NULL, 'Common', 1),
  (84, 'Horned Lark', NULL, 'Common', 1),
  (85, 'Pacific Loon', NULL, 'Common', 1),
  (86, 'Mallard', NULL, 'Common', 1),
  (87, 'Western Meadowlark', NULL, 'Common', 1),
  (88, 'Hooded Merganser', NULL, 'Common', 1),
  (89, 'Red breasted Merganser', NULL, 'Common', 1),
  (90, 'Mockingbird', NULL, 'Common', 1),
  (91, 'Nighthawk', NULL, 'Common', 1),
  (92, 'Clark Nutcracker', NULL, 'Common', 1),
  (93, 'White breasted Nuthatch', NULL, 'Common', 1),
  (94, 'Baltimore Oriole', NULL, 'Common', 1),
  (95, 'Hooded Oriole', NULL, 'Common', 1),
  (96, 'Orchard Oriole', NULL, 'Common', 1),
  (97, 'Scott Oriole', NULL, 'Common', 1),
  (98, 'Ovenbird', NULL, 'Common', 1),
  (99, 'Brown Pelican', NULL, 'Common', 1),
  (100, 'White Pelican', NULL, 'Common', 1),
  (101, 'Western Wood Pewee', NULL, 'Common', 1),
  (102, 'Sayornis', NULL, 'Common', 1),
  (103, 'American Pipit', NULL, 'Common', 1),
  (104, 'Whip poor Will', NULL, 'Common', 1),
  (105, 'Horned Puffin', NULL, 'Common', 1),
  (106, 'Common Raven', NULL, 'Common', 1),
  (107, 'White necked Raven', NULL, 'Common', 1),
  (108, 'American Redstart', NULL, 'Common', 1),
  (109, 'Geococcyx', NULL, 'Common', 1),
  (110, 'Loggerhead Shrike', NULL, 'Common', 1),
  (111, 'Great Grey Shrike', NULL, 'Common', 1),
  (112, 'Baird Sparrow', NULL, 'Common', 1),
  (113, 'Black throated Sparrow', NULL, 'Common', 1),
  (114, 'Brewer Sparrow', NULL, 'Common', 1),
  (115, 'Chipping Sparrow', NULL, 'Common', 1),
  (116, 'Clay colored Sparrow', NULL, 'Common', 1),
  (117, 'House Sparrow', NULL, 'Common', 1),
  (118, 'Field Sparrow', NULL, 'Common', 1),
  (119, 'Fox Sparrow', NULL, 'Common', 1),
  (120, 'Grasshopper Sparrow', NULL, 'Common', 1),
  (121, 'Harris Sparrow', NULL, 'Common', 1),
  (122, 'Henslow Sparrow', NULL, 'Common', 1),
  (123, 'Le Conte Sparrow', NULL, 'Common', 1),
  (124, 'Lincoln Sparrow', NULL, 'Common', 1),
  (125, 'Nelson Sharp tailed Sparrow', NULL, 'Common', 1),
  (126, 'Savannah Sparrow', NULL, 'Common', 1),
  (127, 'Seaside Sparrow', NULL, 'Common', 1),
  (128, 'Song Sparrow', NULL, 'Common', 1),
  (129, 'Tree Sparrow', NULL, 'Common', 1),
  (130, 'Vesper Sparrow', NULL, 'Common', 1),
  (131, 'White crowned Sparrow', NULL, 'Common', 1),
  (132, 'White throated Sparrow', NULL, 'Common', 1),
  (133, 'Cape Glossy Starling', NULL, 'Common', 1),
  (134, 'Bank Swallow', NULL, 'Common', 1),
  (135, 'Barn Swallow', NULL, 'Common', 1),
  (136, 'Cliff Swallow', NULL, 'Common', 1),
  (137, 'Tree Swallow', NULL, 'Common', 1),
  (138, 'Scarlet Tanager', NULL, 'Common', 1),
  (139, 'Summer Tanager', NULL, 'Common', 1),
  (140, 'Artic Tern', NULL, 'Common', 1),
  (141, 'Black Tern', NULL, 'Common', 1),
  (142, 'Caspian Tern', NULL, 'Common', 1),
  (143, 'Common Tern', NULL, 'Common', 1),
  (144, 'Elegant Tern', NULL, 'Common', 1),
  (145, 'Forsters Tern', NULL, 'Common', 1),
  (146, 'Least Tern', NULL, 'Common', 1),
  (147, 'Green tailed Towhee', NULL, 'Common', 1),
  (148, 'Brown Thrasher', NULL, 'Common', 1),
  (149, 'Sage Thrasher', NULL, 'Common', 1),
  (150, 'Black capped Vireo', NULL, 'Common', 1),
  (151, 'Blue headed Vireo', NULL, 'Common', 1),
  (152, 'Philadelphia Vireo', NULL, 'Common', 1),
  (153, 'Red eyed Vireo', NULL, 'Common', 1),
  (154, 'Warbling Vireo', NULL, 'Common', 1),
  (155, 'White eyed Vireo', NULL, 'Common', 1),
  (156, 'Yellow throated Vireo', NULL, 'Common', 1),
  (157, 'Bay breasted Warbler', NULL, 'Common', 1),
  (158, 'Black and white Warbler', NULL, 'Common', 1),
  (159, 'Black throated Blue Warbler', NULL, 'Common', 1),
  (160, 'Blue winged Warbler', NULL, 'Common', 1),
  (161, 'Canada Warbler', NULL, 'Common', 1),
  (162, 'Cape May Warbler', NULL, 'Common', 1),
  (163, 'Cerulean Warbler', NULL, 'Common', 1),
  (164, 'Chestnut sided Warbler', NULL, 'Common', 1),
  (165, 'Golden winged Warbler', NULL, 'Common', 1),
  (166, 'Hooded Warbler', NULL, 'Common', 1),
  (167, 'Kentucky Warbler', NULL, 'Common', 1),
  (168, 'Magnolia Warbler', NULL, 'Common', 1),
  (169, 'Mourning Warbler', NULL, 'Common', 1),
  (170, 'Myrtle Warbler', NULL, 'Common', 1),
  (171, 'Nashville Warbler', NULL, 'Common', 1),
  (172, 'Orange crowned Warbler', NULL, 'Common', 1),
  (173, 'Palm Warbler', NULL, 'Common', 1),
  (174, 'Pine Warbler', NULL, 'Common', 1),
  (175, 'Prairie Warbler', NULL, 'Common', 1),
  (176, 'Prothonotary Warbler', NULL, 'Common', 1),
  (177, 'Swainson Warbler', NULL, 'Common', 1),
  (178, 'Tennessee Warbler', NULL, 'Common', 1),
  (179, 'Wilson Warbler', NULL, 'Common', 1),
  (180, 'Worm eating Warbler', NULL, 'Common', 1),
  (181, 'Yellow Warbler', NULL, 'Common', 1),
  (182, 'Northern Waterthrush', NULL, 'Common', 1),
  (183, 'Louisiana Waterthrush', NULL, 'Common', 1),
  (184, 'Bohemian Waxwing', NULL, 'Common', 1),
  (185, 'Cedar Waxwing', NULL, 'Common', 1),
  (186, 'American Three toed Woodpecker', NULL, 'Common', 1),
  (187, 'Pileated Woodpecker', NULL, 'Common', 1),
  (188, 'Red bellied Woodpecker', NULL, 'Common', 1),
  (189, 'Red cockaded Woodpecker', NULL, 'Common', 1),
  (190, 'Red headed Woodpecker', NULL, 'Common', 1),
  (191, 'Downy Woodpecker', NULL, 'Common', 1),
  (192, 'Bewick Wren', NULL, 'Common', 1),
  (193, 'Cactus Wren', NULL, 'Common', 1),
  (194, 'Carolina Wren', NULL, 'Common', 1),
  (195, 'House Wren', NULL, 'Common', 1),
  (196, 'Marsh Wren', NULL, 'Common', 1),
  (197, 'Rock Wren', NULL, 'Common', 1),
  (198, 'Winter Wren', NULL, 'Common', 1),
  (199, 'Common Yellowthroat', NULL, 'Common', 1)
on conflict (class_index) do update
  set common_name = excluded.common_name;
